version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.local
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

networks:
  default:
    name: nami_navigation_log

volumes:
  postgres: